name: Intra Epitech Client CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: '16.x'
      - name: Install dependencies 
        run: npm install
      - name: Run Linter
        run: npm run lint

  check_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies 
        run: npm install
      - name: Run tests & get code coverage
        run: npm test
        env:
          CI: true
          EPITECH_COOKIE: ${{ secrets.EPITECH_COOKIE }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  deploy:
    runs-on: ubuntu-latest
    needs: [check_lint, check_tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies 
        run: npm install
      - name: Bump version
        run: npm version patch
      - name: Build
        run: npm run build
      - name: NPM CI
        run: npm ci
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          EPITECH_COOKIE: ${{ secrets.EPITECH_COOKIE }}
